#!/usr/bin/env python3

# This is a wrapper around xmllint to emulate the "bad behavior"
# of some xmllint versions that return an exit code 0 even if the
# validation fails. It requires the full path to the "real" xmllint
# executable to be defined as environment variable XMLLINT_REAL

import os
import shutil
import subprocess
import sys

xmllint = os.getenv("XMLLINT_REAL")
if not xmllint:
    raise Exception("xmllint not found")

cmd = [xmllint] + sys.argv[1:]
cproc = subprocess.run(cmd, check=False, capture_output=True)
if cproc.stdout:
    sys.stdout.write(cproc.stdout.decode('utf-8', errors='replace').strip()+"\n")
if cproc.stderr:
    sys.stderr.write(cproc.stderr.decode('utf-8', errors='replace').strip()+"\n")
# Exit with an exit code of zero no matter what
sys.exit(0)
