#!/usr/bin/env python3

"""Generate ``ccpp_host_constituents.F90`` — the host-wide constituent module.

In capgen's per-instance design, the constituent state is sized to
``number_of_instances`` (declared by the host's ``type=control`` table,
paired with ``instance_number``).
This module owns:

* ``ccpp_model_constituents_obj(:)`` — one DDT instance per host
  instance, lazily allocated on first ``ccpp_register_constituents``.
* Per-suite buffers ``<suite>_dynamic_constituents(:)`` — populated by
  ``<suite>_register`` from register-phase scheme call results.
  Single-dim because registration is identical across instances; the
  first instance fills the buffer and subsequent instances skip.
* ``index_of_<X>`` integers (module-level scalars; identical across
  instances) — bound by ``ccpp_initialize_constituents`` via
  ``%const_index`` queries.
* ``ccpp_model_const_stdnames`` parameter array listing the std names
  known to capgen at code-generation time.

Host-facing API mirrors original capgen but every routine that touches
a specific instance's state takes ``instance_number`` (when the host
declares it).  Scheme call sites generated by the resolver access
``ccpp_model_constituents_obj(<inst>)%vars_layer(…)`` directly, so the
old module-level pointer bindings (``ccpp_constituents`` etc.) have
been removed.
"""

import logging
import os
from typing import List, Optional, Set, Tuple

from metadata.parse_tools import open_if_changed
from generator.suite_resolver import SuiteResolution, _index_symbol_name

_INDENT = '  '

_HOST_CONST_MOD      = 'ccpp_host_constituents'
_CONST_PROP_MOD      = 'ccpp_constituent_prop_mod'
_CONST_DDT           = 'ccpp_model_constituents_t'
_CONST_PROP_TYPE     = 'ccpp_constituent_properties_t'
_CONST_PROP_PTR_TYPE = 'ccpp_constituent_prop_ptr_t'

# Public name of the host-wide constituent object (now a per-instance
# allocatable array).
_CONST_OBJ = 'ccpp_model_constituents_obj'


########################################################################
# Aggregation helpers
########################################################################

def _any_constituent_state(suite_results: List[SuiteResolution]) -> bool:
    """Return True iff any suite either uses or registers constituents."""
    return any(
        suite_resolution.uses_constituents or suite_resolution.constituent_register_calls
        for suite_resolution in suite_results
    )


def _all_index_names(suite_results: List[SuiteResolution]) -> List[str]:
    """Return sorted unique base std-names that need an ``index_of_<X>``."""
    names: Set[str] = set()
    for suite_resolution in suite_results:
        names.update(suite_resolution.constituent_index_names)
    return sorted(names)


def _suites_with_register_consts(
    suite_results: List[SuiteResolution],
) -> List[str]:
    # auto-clone-constituents: predicate is centralised on
    # SuiteResolution so this module never reads legacy-shim state
    # directly; see ``SuiteResolution.needs_dynamic_constituents_buffer``.
    return [sr.suite_name for sr in suite_results
            if sr.needs_dynamic_constituents_buffer]


def _dyn_const_array_name(suite_name: str) -> str:
    return '{}_dynamic_constituents'.format(suite_name)


def _host_lookup(host_dict, std_name: str) -> Tuple[Optional[str], Optional[str]]:
    """Return (local_name, module_name) for *std_name* in *host_dict*.

    Returns ``(None, None)`` when the entry is absent or is a control var.
    """
    if not host_dict:
        return None, None
    entry = host_dict.get(std_name)
    if entry is None:
        return None, None
    return entry.local_name, entry.module_name


########################################################################
# Per-routine emitters
########################################################################

def _instance_signature(
    base_args: List[str],
    inst_local: Optional[str],
    ninst_local: Optional[str] = None,
) -> List[str]:
    """Return signature args with *inst_local* and (optionally)
    *ninst_local* inserted before err args."""
    sig = list(base_args)
    if inst_local:
        sig.append(inst_local)
    if ninst_local:
        sig.append(ninst_local)
    sig += ['errcode', 'errmsg']
    return sig


def _register_constituents_lines(
    suite_results: List[SuiteResolution],
    host_dict,
) -> List[str]:
    """Emit ``ccpp_register_constituents``."""
    i1 = _INDENT
    i2 = _INDENT * 2
    i3 = _INDENT * 3
    register_suites = _suites_with_register_consts(suite_results)
    inst_local, _ = _host_lookup(host_dict, 'instance_number')
    # ``number_of_instances`` is now a paired control variable; it arrives
    # as a dummy argument rather than via ``use <host_mod>``.  Its module
    # is ``None`` (control vars carry no module), so ninst_mod is ignored.
    ninst_local, _ = _host_lookup(host_dict, 'number_of_instances')
    inst_idx     = inst_local if inst_local else '1'
    ninst_arg    = ninst_local if ninst_local else '1'

    sig = _instance_signature(
        ['host_constituents'], inst_local, ninst_local=ninst_local,
    )
    lines: List[str] = ['']
    lines.append('{}subroutine ccpp_register_constituents({})'.format(
        i1, ', '.join(sig),
    ))
    lines.append('')
    lines.append(
        '{}type({}), target, intent(in) :: host_constituents(:)'.format(
            i2, _CONST_PROP_TYPE,
        )
    )
    if inst_local:
        lines.append('{}integer, intent(in) :: {}'.format(i2, inst_local))
    if ninst_local:
        lines.append('{}integer, intent(in) :: {}'.format(i2, ninst_local))
    lines.append('{}integer, intent(out) :: errcode'.format(i2))
    lines.append('{}character(len=*), intent(out) :: errmsg'.format(i2))
    lines.append('')
    lines.append('{}integer :: num_consts, index'.format(i2))
    lines.append('{}type({}), pointer :: const_prop => null()'.format(
        i2, _CONST_PROP_TYPE,
    ))
    lines.append('')
    lines.append("{}errmsg = ''".format(i2))
    lines.append('{}errcode = 0'.format(i2))
    lines.append('')
    # Allocate the object array on first call (idempotent across instances).
    lines.append('{}if (.not. allocated({})) then'.format(i2, _CONST_OBJ))
    lines.append('{}allocate({}({}))'.format(i3, _CONST_OBJ, ninst_arg))
    lines.append('{}end if'.format(i2))
    lines.append('')
    # Count.
    lines.append('{}num_consts = size(host_constituents, 1)'.format(i2))
    for sname in register_suites:
        buf = _dyn_const_array_name(sname)
        lines.append('{}if (allocated({})) then'.format(i2, buf))
        lines.append(
            '{}if (allocated({}({})%items)) then'.format(i3, buf, inst_idx)
        )
        lines.append(
            '{}num_consts = num_consts + size({}({})%items, 1)'.format(
                i3 + _INDENT, buf, inst_idx,
            )
        )
        lines.append('{}end if'.format(i3))
        lines.append('{}end if'.format(i2))
    lines.append('')
    lines.append('{}call {}({})%initialize_table(num_consts)'.format(
        i2, _CONST_OBJ, inst_idx,
    ))
    lines.append('')
    # Host constituents first.
    lines.append('{}do index = 1, size(host_constituents, 1)'.format(i2))
    lines.append('{}const_prop => host_constituents(index)'.format(i3))
    lines.append(
        '{}call {}({})%new_field(const_prop, errcode=errcode, errmsg=errmsg)'.format(
            i3, _CONST_OBJ, inst_idx,
        )
    )
    lines.append('{}nullify(const_prop)'.format(i3))
    lines.append('{}if (errcode /= 0) return'.format(i3))
    lines.append('{}end do'.format(i2))
    for sname in register_suites:
        buf = _dyn_const_array_name(sname)
        lines.append('')
        lines.append("{}! Merge {} dynamic constituents".format(i2, sname))
        lines.append('{}if (allocated({})) then'.format(i2, buf))
        lines.append(
            '{}if (allocated({}({})%items)) then'.format(i3, buf, inst_idx)
        )
        lines.append(
            '{}do index = 1, size({}({})%items, 1)'.format(
                i3 + _INDENT, buf, inst_idx,
            )
        )
        lines.append(
            '{}const_prop => {}({})%items(index)'.format(
                i3 + _INDENT * 2, buf, inst_idx,
            )
        )
        lines.append(
            '{}call {}({})%new_field(const_prop, errcode=errcode, errmsg=errmsg)'.format(
                i3 + _INDENT * 2, _CONST_OBJ, inst_idx,
            )
        )
        lines.append('{}nullify(const_prop)'.format(i3 + _INDENT * 2))
        lines.append('{}if (errcode /= 0) return'.format(i3 + _INDENT * 2))
        lines.append('{}end do'.format(i3 + _INDENT))
        lines.append('{}end if'.format(i3))
        lines.append('{}end if'.format(i2))
    lines.append('')
    lines.append(
        '{}call {}({})%lock_table(errcode=errcode, errmsg=errmsg)'.format(
            i2, _CONST_OBJ, inst_idx,
        )
    )
    lines.append('')
    lines.append('{}end subroutine ccpp_register_constituents'.format(i1))
    return lines


def _initialize_constituents_lines(
    suite_results: List[SuiteResolution],
    host_dict,
) -> List[str]:
    """Emit ``ccpp_initialize_constituents``."""
    i1 = _INDENT
    i2 = _INDENT * 2
    inst_local, _ = _host_lookup(host_dict, 'instance_number')
    inst_idx = inst_local if inst_local else '1'
    index_names = _all_index_names(suite_results)

    sig = _instance_signature(['ncols', 'num_layers'], inst_local)
    lines: List[str] = ['']
    lines.append('{}subroutine ccpp_initialize_constituents({})'.format(
        i1, ', '.join(sig),
    ))
    lines.append(
        '{}use ccpp_scheme_utils, only: ccpp_initialize_constituent_ptr'.format(i2)
    )
    lines.append('')
    lines.append('{}integer, intent(in) :: ncols, num_layers'.format(i2))
    if inst_local:
        lines.append('{}integer, intent(in) :: {}'.format(i2, inst_local))
    lines.append('{}integer, intent(out) :: errcode'.format(i2))
    lines.append('{}character(len=*), intent(out) :: errmsg'.format(i2))
    lines.append('')
    lines.append('{}type({}), pointer :: const_obj_ptr => null()'.format(
        i2, _CONST_DDT,
    ))
    lines.append('')
    lines.append("{}errmsg = ''".format(i2))
    lines.append('{}errcode = 0'.format(i2))
    lines.append('')
    lines.append(
        '{}call {}({})%lock_data(ncols, num_layers, errcode=errcode, errmsg=errmsg)'.format(
            i2, _CONST_OBJ, inst_idx,
        )
    )
    lines.append('{}if (errcode /= 0) return'.format(i2))
    # Cache the singleton pointer in ccpp_scheme_utils (cam-sima compat).
    # Only the FIRST call across instances actually sets it (the routine
    # is guarded internally); other instances see the first instance's
    # object when they call ccpp_constituent_index — a known limitation
    # of the framework's scheme_utils for multi-instance hosts.
    lines.append('{}const_obj_ptr => {}({})'.format(
        i2, _CONST_OBJ, inst_idx,
    ))
    lines.append('{}call ccpp_initialize_constituent_ptr(const_obj_ptr)'.format(i2))
    lines.append('{}nullify(const_obj_ptr)'.format(i2))
    lines.append('')
    for std_name in index_names:
        index_sym = _index_symbol_name(std_name)
        lines.append(
            "{}call {}({})%const_index({}, '{}', "
            "errcode=errcode, errmsg=errmsg)".format(
                i2, _CONST_OBJ, inst_idx, index_sym, std_name,
            )
        )
        lines.append('{}if (errcode /= 0) return'.format(i2))
        # %const_index doesn't error on a miss — it sets the integer to
        # int_unassigned and leaves errcode unchanged.  Surface that case
        # explicitly so the host sees the bad registration at init time
        # instead of crashing on a -huge(1) subscript later.
        lines.append(
            '{}if ({} == int_unassigned) then'.format(
                i2, index_sym,
            )
        )
        lines.append('{}errcode = 1'.format(i2 + _INDENT))
        lines.append(
            "{}errmsg = 'ccpp_initialize_constituents: constituent "
            "''{}'' is referenced by a scheme but is not in the "
            "registered constituent table; check that some scheme'"
            "'s _register routine or the host_constituents argument "
            "to ccpp_register_constituents includes it'".format(
                i2 + _INDENT, std_name,
            )
        )
        lines.append('{}return'.format(i2 + _INDENT))
        lines.append('{}end if'.format(i2))
    lines.append('')
    lines.append('{}end subroutine ccpp_initialize_constituents'.format(i1))
    return lines


def _is_scheme_constituent_lines(suite_results: List[SuiteResolution]) -> List[str]:
    """Emit ``ccpp_is_scheme_constituent`` (no instance_number — module-level)."""
    i1 = _INDENT
    i2 = _INDENT * 2
    index_names = _all_index_names(suite_results)
    lines: List[str] = ['']
    lines.append(
        '{}subroutine ccpp_is_scheme_constituent(var_name, '
        'constituent_exists, errcode, errmsg)'.format(i1)
    )
    lines.append('')
    lines.append('{}character(len=*), intent(in)  :: var_name'.format(i2))
    lines.append('{}logical,          intent(out) :: constituent_exists'.format(i2))
    lines.append('{}integer,          intent(out) :: errcode'.format(i2))
    lines.append('{}character(len=*), intent(out) :: errmsg'.format(i2))
    lines.append('')
    lines.append("{}errmsg = ''".format(i2))
    lines.append('{}errcode = 0'.format(i2))
    lines.append('')
    if index_names:
        lines.append(
            '{}constituent_exists = any(ccpp_model_const_stdnames == var_name)'.format(i2)
        )
    else:
        lines.append('{}constituent_exists = .false.'.format(i2))
    lines.append('')
    lines.append('{}end subroutine ccpp_is_scheme_constituent'.format(i1))
    return lines


def _wrap_method_sub(
    sub_name: str,
    method: str,
    extra_args: List[Tuple[str, str, str]],
    inst_local: Optional[str],
    errcode_call: bool = True,
) -> List[str]:
    """Thin wrapper subroutine calling ``obj(inst_num)%method(...)``."""
    i1 = _INDENT
    i2 = _INDENT * 2
    inst_idx = inst_local if inst_local else '1'
    sig = [n for n, _, _ in extra_args]
    if inst_local:
        sig.append(inst_local)
    sig += ['errcode', 'errmsg']
    lines: List[str] = ['']
    lines.append('{}subroutine {}({})'.format(i1, sub_name, ', '.join(sig)))
    lines.append('')
    for _, decl, _ in extra_args:
        lines.append('{}{}'.format(i2, decl))
    if inst_local:
        lines.append('{}integer, intent(in) :: {}'.format(i2, inst_local))
    lines.append('{}integer, intent(out) :: errcode'.format(i2))
    lines.append('{}character(len=*), intent(out) :: errmsg'.format(i2))
    lines.append('')
    lines.append("{}errmsg = ''".format(i2))
    lines.append('{}errcode = 0'.format(i2))
    lines.append('')
    call_args = [call for _, _, call in extra_args]
    if errcode_call:
        call_args += ['errcode=errcode', 'errmsg=errmsg']
    lines.append('{}call {}({})%{}({})'.format(
        i2, _CONST_OBJ, inst_idx, method, ', '.join(call_args),
    ))
    lines.append('')
    lines.append('{}end subroutine {}'.format(i1, sub_name))
    return lines


def _wrap_method_subs(host_dict) -> List[str]:
    inst_local, _ = _host_lookup(host_dict, 'instance_number')
    lines: List[str] = []
    lines.extend(_wrap_method_sub(
        'ccpp_number_constituents', 'num_constituents',
        [
            ('num_flds', 'integer, intent(out) :: num_flds', 'num_flds'),
            ('advected', 'logical, optional, intent(in) :: advected',
             'advected=advected'),
        ],
        inst_local,
    ))
    lines.extend(_wrap_method_sub(
        'ccpp_gather_constituents', 'copy_in',
        [('const_array',
          'real(kind=kind_phys), intent(out) :: const_array(:,:,:)',
          'const_array')],
        inst_local,
    ))
    lines.extend(_wrap_method_sub(
        'ccpp_update_constituents', 'copy_out',
        [('const_array',
          'real(kind=kind_phys), intent(in) :: const_array(:,:,:)',
          'const_array')],
        inst_local,
    ))
    lines.extend(_wrap_method_sub(
        'ccpp_const_get_index', 'const_index',
        [
            ('stdname', 'character(len=*), intent(in) :: stdname',
             'standard_name=stdname'),
            ('const_index', 'integer, intent(out) :: const_index',
             'index=const_index'),
        ],
        inst_local,
    ))
    return lines


def _accessor_functions(host_dict) -> List[str]:
    """Pointer-returning accessor functions, indexed by instance_number."""
    i1 = _INDENT
    i2 = _INDENT * 2
    inst_local, _ = _host_lookup(host_dict, 'instance_number')
    inst_idx = inst_local if inst_local else '1'
    args = '({})'.format(inst_local) if inst_local else '()'
    decl = ('integer, intent(in) :: {}'.format(inst_local)
            if inst_local else '')

    def _emit(fname, method, ret_decl):
        out = [
            '',
            '{}function {}{} result(const_ptr)'.format(i1, fname, args),
            '{}{}'.format(i2, ret_decl),
        ]
        if decl:
            out.append('{}{}'.format(i2, decl))
        out += [
            '{}const_ptr => {}({})%{}()'.format(
                i2, _CONST_OBJ, inst_idx, method,
            ),
            '{}end function {}'.format(i1, fname),
        ]
        return out

    lines: List[str] = []
    lines += _emit(
        'ccpp_constituents_array', 'field_data_ptr',
        'real(kind=kind_phys), pointer :: const_ptr(:,:,:)',
    )
    lines += _emit(
        'ccpp_advected_constituents_array', 'advected_constituents_ptr',
        'real(kind=kind_phys), pointer :: const_ptr(:,:,:)',
    )
    # Properties function returns a different pointer type.
    fname = 'ccpp_model_const_properties'
    ret_decl = 'type({}), pointer :: const_ptr(:)'.format(_CONST_PROP_PTR_TYPE)
    args_props = '({})'.format(inst_local) if inst_local else '()'
    lines += [
        '',
        '{}function {}{} result(const_ptr)'.format(i1, fname, args_props),
        '{}{}'.format(i2, ret_decl),
    ]
    if decl:
        lines.append('{}{}'.format(i2, decl))
    lines += [
        '{}const_ptr => {}({})%constituent_props_ptr()'.format(
            i2, _CONST_OBJ, inst_idx,
        ),
        '{}end function {}'.format(i1, fname),
    ]
    return lines


def _deallocate_lines(
    suite_results: List[SuiteResolution],
    host_dict,
) -> List[str]:
    """Emit ``ccpp_deallocate_dynamic_constituents`` — per-instance with
    last-to-leave teardown.

    Each call resets the constituent object for the given instance.  When
    every instance's object has been reset (none still has its property
    table locked), the per-suite dynamic-constituent buffers and the
    object array itself are deallocated, and the cached
    ``index_of_<X>`` integers are reset.

    Mirrors the per-instance + last-to-leave pattern used by
    ``<suite>_final`` in the suite cap.
    """
    i1 = _INDENT
    i2 = _INDENT * 2
    i3 = _INDENT * 3
    register_suites = _suites_with_register_consts(suite_results)
    index_names = _all_index_names(suite_results)
    inst_local, _ = _host_lookup(host_dict, 'instance_number')
    inst_idx = inst_local if inst_local else '1'

    sig_args = [inst_local] if inst_local else []

    lines: List[str] = ['']
    lines.append('{}subroutine ccpp_deallocate_dynamic_constituents({})'.format(
        i1, ', '.join(sig_args),
    ))
    lines.append('')
    if inst_local:
        lines.append('{}integer, intent(in) :: {}'.format(i2, inst_local))
    lines.append('')
    lines.append('{}integer :: i'.format(i2))
    lines.append('{}logical :: all_done'.format(i2))
    lines.append('')
    lines.append('{}if (.not. allocated({})) return'.format(i2, _CONST_OBJ))
    lines.append('')
    # Per-instance reset.
    lines.append('{}call {}({})%reset()'.format(i2, _CONST_OBJ, inst_idx))
    lines.append('')
    # Last-to-leave: when no instance still has its constituent table
    # locked, tear down everything (buffers + object array + indices).
    lines.append('{}all_done = .true.'.format(i2))
    lines.append('{}do i = 1, size({}, 1)'.format(i2, _CONST_OBJ))
    lines.append('{}if ({}(i)%const_props_locked()) then'.format(
        i3, _CONST_OBJ,
    ))
    lines.append('{}all_done = .false.'.format(i3 + _INDENT))
    lines.append('{}exit'.format(i3 + _INDENT))
    lines.append('{}end if'.format(i3))
    lines.append('{}end do'.format(i2))
    lines.append('')
    lines.append('{}if (all_done) then'.format(i2))
    # The per-suite ``<suite>_dynamic_constituents`` buffers are NOT
    # deallocated here.  They're owned by the suite-cap lifecycle (filled
    # by ``<suite>_register``, gated by the suite-cap state machine), so
    # tearing them down independently would leave the suite_state in a
    # state where the next ``ccpp_register`` short-circuits via the
    # ``state >= REGISTERED`` guard and the buffer never gets re-filled.
    # They are deallocated in ``<suite>_final``'s last-to-leave block
    # instead.
    lines.append('{}deallocate({})'.format(i3, _CONST_OBJ))
    # Reset to the unbound sentinel (matches the declaration default) so a
    # re-register / re-init cycle starts from int_unassigned and the guard
    # stays effective on the second pass.
    for std_name in index_names:
        lines.append('{}{} = int_unassigned'.format(
            i3, _index_symbol_name(std_name)))
    lines.append('{}end if'.format(i2))
    lines.append('')
    lines.append('{}end subroutine ccpp_deallocate_dynamic_constituents'.format(i1))
    return lines


########################################################################
# Top-level generator
########################################################################

def _generate_host_constituents(
    suite_results: List[SuiteResolution],
    host_dict=None,
) -> Optional[List[str]]:
    """Generate ``ccpp_host_constituents.F90`` source lines, or ``None``."""
    if not _any_constituent_state(suite_results):
        return None

    register_suites = _suites_with_register_consts(suite_results)
    index_names     = _all_index_names(suite_results)

    lines: List[str] = []
    lines.append(
        '! ccpp_host_constituents.F90 -- generated by ccpp_capgen, do not edit'
    )
    lines.append('module {}'.format(_HOST_CONST_MOD))
    lines.append('')
    lines.append('{}use ccpp_kinds, only: kind_phys'.format(_INDENT))
    lines.append('{}use {}, only: &'.format(_INDENT, _CONST_PROP_MOD))
    lines.append('{}{}, &'.format(_INDENT * 2, _CONST_DDT))
    lines.append('{}{}, &'.format(_INDENT * 2, _CONST_PROP_TYPE))
    lines.append('{}{}, &'.format(_INDENT * 2, _CONST_PROP_PTR_TYPE))
    # int_unassigned is the sentinel returned by %const_index when a
    # standard name is not in the constituent table.  Used by
    # ccpp_initialize_constituents to validate that every cached
    # index_of_<X> integer corresponds to an actually-registered
    # constituent — surfaces missing-registration bugs at init time
    # instead of letting them become silent invalid array accesses
    # later in run-phase scheme calls.
    lines.append('{}int_unassigned'.format(_INDENT * 2))
    lines.append('')
    lines.append('{}implicit none'.format(_INDENT))
    lines.append('{}private'.format(_INDENT))
    lines.append('')

    # Publics: state + routines.
    publics = [_CONST_OBJ]
    publics += [_index_symbol_name(n) for n in index_names]
    publics += [
        'ccpp_register_constituents',
        'ccpp_initialize_constituents',
        'ccpp_is_scheme_constituent',
        'ccpp_number_constituents',
        'ccpp_gather_constituents',
        'ccpp_update_constituents',
        'ccpp_const_get_index',
        'ccpp_constituents_array',
        'ccpp_advected_constituents_array',
        'ccpp_model_const_properties',
        'ccpp_deallocate_dynamic_constituents',
    ]
    if index_names:
        publics.append('ccpp_model_const_stdnames')
    publics += [_dyn_const_array_name(s) for s in register_suites]
    for p in publics:
        lines.append('{}public :: {}'.format(_INDENT, p))
    lines.append('')

    # Per-instance wrapper around the per-suite scheme-registered
    # constituent buffer.  Each instance owns its own slot in the outer
    # array; the inner ``items(:)`` array is filled independently by
    # ``<suite>_register`` per instance so that the property objects
    # (which acquire a const_ind during ``ccpp_register_constituents``)
    # are not shared across instances.
    if register_suites:
        lines.append(
            '{}type :: ccpp_dyn_const_buffer_t'.format(_INDENT)
        )
        lines.append(
            '{}type({}), allocatable :: items(:)'.format(
                _INDENT * 2, _CONST_PROP_TYPE,
            )
        )
        lines.append(
            '{}end type ccpp_dyn_const_buffer_t'.format(_INDENT)
        )
        lines.append('')

    # State declarations.
    lines.append(
        '{}type({}), target, allocatable :: {}(:)'.format(
            _INDENT, _CONST_DDT, _CONST_OBJ,
        )
    )
    lines.append('')
    for sname in register_suites:
        buf = _dyn_const_array_name(sname)
        lines.append(
            '{}type(ccpp_dyn_const_buffer_t), allocatable, target :: {}(:)'.format(
                _INDENT, buf,
            )
        )
    if register_suites:
        lines.append('')
    # Default to int_unassigned (NOT 0) so a constituent that is referenced
    # by a scheme but never bound by ccpp_initialize_constituents (missing
    # registration, or a host that never calls the init routine) is caught
    # by the post-const_index guard below instead of silently surviving as
    # an index of 0 and producing an out-of-bounds vars_layer subscript at
    # run time.  This also keeps the guard correct for any framework whose
    # %const_index leaves the output unchanged on a name miss.
    for std_name in index_names:
        lines.append('{}integer :: {} = int_unassigned'.format(
            _INDENT, _index_symbol_name(std_name)))
    if index_names:
        max_len = max(len(n) for n in index_names)
        lines.append('')
        lines.append(
            '{}character(len={}), parameter :: ccpp_model_const_stdnames({}) = (/ &'.format(
                _INDENT, max_len, len(index_names),
            )
        )
        for i, std_name in enumerate(index_names):
            sep = ', &' if i < len(index_names) - 1 else ' /)'
            padding = ' ' * (max_len - len(std_name))
            lines.append("{}'{}{}'{}".format(_INDENT * 2, std_name, padding, sep))
    lines.append('')
    lines.append('contains')

    lines.extend(_register_constituents_lines(suite_results, host_dict))
    lines.extend(_initialize_constituents_lines(suite_results, host_dict))
    lines.extend(_is_scheme_constituent_lines(suite_results))
    lines.extend(_wrap_method_subs(host_dict))
    lines.extend(_accessor_functions(host_dict))
    lines.extend(_deallocate_lines(suite_results, host_dict))

    lines.append('')
    lines.append('end module {}'.format(_HOST_CONST_MOD))
    return lines


def write_host_constituents(
    suite_results: List[SuiteResolution],
    outdir: str,
    host_dict=None,
    logger: Optional[logging.Logger] = None,
) -> Optional[str]:
    """Write ``ccpp_host_constituents.F90`` if needed, return its path or ``None``."""
    lines = _generate_host_constituents(suite_results, host_dict)
    if lines is None:
        return None
    if not os.path.isdir(outdir):
        os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, 'ccpp_host_constituents.F90')
    with open_if_changed(path, logger=logger) as fh:
        fh.write('\n'.join(lines) + '\n')
    return os.path.abspath(path)
