#!/usr/bin/env python3

"""Write the ``ccpp_kinds.F90`` module from ``--kind-type`` mappings.

This is the simplest generated file -- a single Fortran module that re-exports
host-supplied kind parameters as ``integer, parameter, public`` constants.

Each kind is described by a ``(module, spec)`` pair: the Fortran module that
defines the precision constant (``module``) and the name of that constant
(``spec``).  When the spec is a standard ``ISO_FORTRAN_ENV`` name (e.g.
``REAL64``), the user may omit the module on the command line and it defaults
to ``iso_fortran_env``.  When the host supplies its own kind module, the
caller passes ``(<my_kinds_mod>, <kind_in_that_mod>)``.

Example output for ``--kind-type kind_phys=REAL64`` (default module)::

    ! ccpp_kinds.F90 -- generated by ccpp_capgen, do not edit
    module ccpp_kinds
      use iso_fortran_env, only: REAL64

      implicit none
      private

      integer, parameter, public :: kind_phys = REAL64

    end module ccpp_kinds

Example output for ``--kind-type kind_phys=my_host_kinds:kind_r8`` (host module)::

    ! ccpp_kinds.F90 -- generated by ccpp_capgen, do not edit
    module ccpp_kinds
      use my_host_kinds, only: kind_r8

      implicit none
      private

      integer, parameter, public :: kind_phys = kind_r8

    end module ccpp_kinds

``ccpp_kinds.F90`` is always generated and is a dependency of all other
generated Fortran files that reference any kind parameter.
"""

import logging
import os
from typing import Dict, List, Optional, Tuple

from metadata.parse_tools import CCPPError, open_if_changed

_KINDS_FILENAME = 'ccpp_kinds.F90'
_KINDS_MODULE   = 'ccpp_kinds'

# Mapping from kind name to a (module, spec) pair.
KindSpec = Tuple[str, str]
KindMap  = Dict[str, KindSpec]


########################################################################
# Public API
########################################################################

def write_ccpp_kinds(
    kind_types: KindMap,
    output_root: str,
    logger: Optional[logging.Logger] = None,
) -> str:
    """Write ``ccpp_kinds.F90`` to *output_root*.

    Parameters
    ----------
    kind_types : dict
        Mapping ``kind_name -> (module_name, kind_spec)``.  Example::

            {'kind_phys': ('iso_fortran_env', 'REAL64'),
             'kind_dyn':  ('my_host_kinds',   'kind_r4')}

    output_root : str
        Directory where the file is written (created if absent).

    Returns
    -------
    str
        Absolute path of the written file.

    Raises
    ------
    CCPPError
        If *kind_types* is empty.
    """
    os.makedirs(output_root, exist_ok=True)
    lines = _generate_ccpp_kinds(kind_types)
    out_path = os.path.join(output_root, _KINDS_FILENAME)
    with open_if_changed(out_path, logger=logger) as fh:
        fh.write('\n'.join(lines) + '\n')
    return out_path


########################################################################
# Internal generator
########################################################################

def _generate_ccpp_kinds(kind_types: KindMap) -> List[str]:
    """Generate the ccpp_kinds module source as a list of lines.

    Lines do not carry trailing newlines.  The caller joins them and
    appends a final newline.

    Parameters
    ----------
    kind_types : dict
        Mapping ``kind_name -> (module_name, kind_spec)``.  Keys are sorted
        alphabetically in the output; ``use`` lines are grouped by module
        and sorted alphabetically by module name.

    Returns
    -------
    list of str

    Raises
    ------
    CCPPError
        If *kind_types* is empty.

    Examples
    --------
    >>> lines = _generate_ccpp_kinds({'kind_phys': ('iso_fortran_env', 'REAL64')})
    >>> lines[0]
    '! ccpp_kinds.F90 -- generated by ccpp_capgen, do not edit'
    >>> 'module ccpp_kinds' in lines
    True
    >>> any('kind_phys' in l and 'REAL64' in l for l in lines)
    True
    >>> 'end module ccpp_kinds' in lines
    True

    Two distinct kinds, both from ``iso_fortran_env``:

    >>> lines = _generate_ccpp_kinds({
    ...     'kind_phys': ('iso_fortran_env', 'REAL64'),
    ...     'kind_dyn':  ('iso_fortran_env', 'REAL32'),
    ... })
    >>> sum(1 for l in lines if 'parameter' in l and 'public' in l)
    2
    >>> sum(1 for l in lines if 'use iso_fortran_env' in l)
    1
    >>> any('REAL32' in l and 'REAL64' in l for l in lines)
    True

    Two kinds sharing the same spec name -- the spec is listed once:

    >>> lines = _generate_ccpp_kinds({
    ...     'a': ('iso_fortran_env', 'REAL64'),
    ...     'b': ('iso_fortran_env', 'REAL64'),
    ... })
    >>> sum(1 for l in lines if 'REAL64' in l and 'iso_fortran_env' in l)
    1

    Host-supplied module:

    >>> lines = _generate_ccpp_kinds({
    ...     'kind_phys': ('my_host_kinds', 'kind_r8'),
    ... })
    >>> any('use my_host_kinds, only: kind_r8' in l for l in lines)
    True
    >>> any('kind_phys = kind_r8' in l for l in lines)
    True

    Empty mapping is an error:

    >>> _generate_ccpp_kinds({})  # doctest: +ELLIPSIS
    Traceback (most recent call last):
        ...
    metadata.parse_tools.parse_source.CCPPError: ccpp_kinds requires at least ...
    """
    if not kind_types:
        raise CCPPError(
            "ccpp_kinds requires at least one kind mapping; "
            "this is a generator bug -- the caller should inject "
            "kind_phys=iso_fortran_env:REAL64 when no --kind-type is given"
        )

    # Group specs by module: {module: sorted_unique_specs}
    by_module: Dict[str, List[str]] = {}
    for _, (mod, spec) in kind_types.items():
        by_module.setdefault(mod, [])
        if spec not in by_module[mod]:
            by_module[mod].append(spec)
    for mod in by_module:
        by_module[mod].sort()

    lines: List[str] = [
        '! ccpp_kinds.F90 -- generated by ccpp_capgen, do not edit',
        'module {}'.format(_KINDS_MODULE),
    ]

    # ``use`` statements -- one per module, alphabetized; specs comma-separated.
    sorted_modules = sorted(by_module)
    use_lines: List[str] = []
    for mod in sorted_modules:
        specs = by_module[mod]
        use_lines.append('  use {}, only: {}'.format(mod, ', '.join(specs)))
    # Column-align the ``only:`` clauses for readability when there is more
    # than one ``use`` line.
    if len(use_lines) > 1:
        max_mod_len = max(len(mod) for mod in sorted_modules)
        use_lines = []
        for mod in sorted_modules:
            pad   = ' ' * (max_mod_len - len(mod))
            specs = by_module[mod]
            use_lines.append(
                '  use {},{} only: {}'.format(mod, pad, ', '.join(specs))
            )
    lines.extend(use_lines)

    lines += [
        '',
        '  implicit none',
        '  private',
        '',
    ]

    # Parameter declarations, column-aligned on '='.
    sorted_kinds = sorted(kind_types.items())
    max_len = max(len(k) for k, _ in sorted_kinds)
    for kind_name, (_mod, spec) in sorted_kinds:
        pad = ' ' * (max_len - len(kind_name))
        lines.append(
            '  integer, parameter, public :: {}{} = {}'.format(
                kind_name, pad, spec
            )
        )

    lines += [
        '',
        'end module {}'.format(_KINDS_MODULE),
    ]

    return lines
