#
# Makefile for HelloWorld example
#

FC              = gfortran

# My dirs
BLDDIR := $(shell pwd -P)
MKFILE_PATH := $(shell dirname $(abspath $(lastword $(MAKEFILE_LIST))))
ROOT = $(shell dirname $(shell dirname $(MKFILE_PATH)))
CAPGEN := $(ROOT)/scripts/ccpp_capgen.py
CAPGEN_ARGS := --host-files $(MKFILE_PATH)/hello_world_host.meta,$(MKFILE_PATH)/hello_world_mod.meta
CAPGEN_ARGS += --scheme-files $(MKFILE_PATH)/hello_scheme.meta,$(MKFILE_PATH)/temp_adjust.meta
CAPGEN_ARGS += --suites $(MKFILE_PATH)/hello_world_suite.xml
CAPGEN_ARGS += --generate-host-cap --host-name HelloWorld
#CAPGEN_ARGS += --verbose --verbose
SRCS_META := $(MKFILE_PATH)/hello_world_host.meta
SRCS_META += $(MKFILE_PATH)/hello_world_mod.meta
SRCS_META += $(MKFILE_PATH)/hello_scheme.meta
SRCS_META += $(MKFILE_PATH)/temp_adjust.meta
SRCS_XML := $(MKFILE_PATH)/hello_world_suite.xml

INCFLAG = -I
INCPATH += $(INCFLAG)$(BLDDIR) $(INCFLAG)$(MKFILE_PATH)
FCFLAGS += -g

# SOURCE FILES
SRCS_F90 = $(MKFILE_PATH)/hello_scheme.F90 $(MKFILE_PATH)/hello_world_host.F90
SRCS_F90 += $(MKFILE_PATH)/hello_world_mod.F90
SRCS_F90 += $(MKFILE_PATH)/temp_adjust.F90
OBJS_F90 = hello_scheme.o temp_adjust.o hello_world_mod.o hello_world_host.o

# Do we have generated CAP files?
$(eval CAPOBJS=$(shell if [ -f caplocal.txt ]; then cat caplocal.txt; fi))

.PHONY: all
all: HelloWorld

# Generate CCPP cap files
capfiles.txt: $(SRCS_META) $(SRCS_XML)
	$(CAPGEN) $(CAPGEN_ARGS)

.PHONY: capobjs
capobjs: capfiles.txt
	$(shell $(MKFILE_PATH)/mkcaplocal.sh $(BLDDIR)/capfiles.txt)
	$(eval CAPOBJS=$(shell cat caplocal.txt))

# Human written
HelloWorld: capobjs $(CAPOBJS) $(OBJS_F90)
	$(FC) $(FCFLAGS) -o $@ $(CAPOBJS) $(OBJS_F90)

hello_scheme.o: ccpp_kinds.o $(MKFILE_PATH)/hello_scheme.F90
	$(FC) -c $(INCPATH) $(FCFLAGS) $(MKFILE_PATH)/hello_scheme.F90

temp_adjust.o: ccpp_kinds.o $(MKFILE_PATH)/temp_adjust.F90
	$(FC) -c $(INCPATH) $(FCFLAGS) $(MKFILE_PATH)/temp_adjust.F90

hello_world_mod.o: ccpp_kinds.o $(MKFILE_PATH)/hello_world_mod.F90
	$(FC) -c $(INCPATH) $(FCFLAGS) $(MKFILE_PATH)/hello_world_mod.F90

hello_world_host.o: HelloWorld_ccpp_cap.o ccpp_kinds.o
hello_world_host.o: $(MKFILE_PATH)/hello_world_host.F90
	$(FC) -c $(INCPATH) $(FCFLAGS) $(MKFILE_PATH)/hello_world_host.F90

# CCPP generated
ccpp_kinds.F90: capobjs

HelloWorld_ccpp_cap.F90: capobjs

ccpp_hello_world_suite_cap.F90: capobjs

ccpp_kinds.o: ccpp_kinds.F90
	$(FC) -c $(INCPATH) $(FCFLAGS) ccpp_kinds.F90

HelloWorld_ccpp_cap.o: ccpp_kinds.o
HelloWorld_ccpp_cap.o: hello_world_mod.o ccpp_hello_world_suite_cap.o
HelloWorld_ccpp_cap.o: HelloWorld_ccpp_cap.F90
	$(FC) -c $(INCPATH) $(FCFLAGS) HelloWorld_ccpp_cap.F90

ccpp_hello_world_suite_cap.o: ccpp_kinds.o ccpp_hello_world_suite_cap.F90
	$(FC) -c $(INCPATH) $(FCFLAGS) ccpp_hello_world_suite_cap.F90

.PHONY: clean
clean:
	rm -f $(shell if [ -f capfiles.txt ]; then cat capfiles.txt; fi)
	rm -f *.o *.mod HelloWorld capfiles.txt caplocal.txt
	rm -rf HelloWorld.dSYM
