#!/usr/bin/env python3

"""Write ``datatable.xml`` — the generator database consumed by ``ccpp_datafile.py``
and CMake to discover compilation targets, scheme modules, and suite structure.

XML layout
----------

Two top-level file sections partition capgen-ng's outputs by language:

* ``<capgen_files>`` lists *Fortran sources only* — utilities, the host-facing
  API, and per-suite cap modules.  All paths here end in ``.F90`` and are
  intended to be compiled by the host build system.
* ``<inspection_files>`` lists *non-Fortran* artifacts — generated
  ``.meta`` files and expanded SDF XML.  These are produced for debugging
  and downstream tooling; they are *not* compiled.

::

    <?xml version="1.0" ?>
    <ccpp_datatable version="1.0">
      <capgen_files>                     <!-- Fortran sources only -->
        <utilities>
          <file>/abs/path/ccpp_kinds.F90</file>
        </utilities>
        <host_files>
          <file>/abs/path/ccpp_static_api.F90</file>
        </host_files>
        <suite_files>
          <file>/abs/path/ccpp_<suite>_cap.F90</file>
          ...
        </suite_files>
      </capgen_files>
      <inspection_files>                <!-- non-Fortran artifacts -->
        <suite_meta_files>
          <file>/abs/path/ccpp_<suite>.meta</file>
          ...
        </suite_meta_files>
        <expanded_sdf_files>
          <file>/abs/path/ccpp_<suite>_expanded.xml</file>
          ...
        </expanded_sdf_files>
      </inspection_files>
      <schemes>
        <scheme name="<scheme>">
          <init name="<scheme>" subroutine_name="<scheme>_init"
                module="<scheme>">
            <call_list>
              <var name="<std_name>" intent="in" local_name="<local>"/>
              ...
            </call_list>
          </init>
          <run .../>
          ...
        </scheme>
        ...
      </schemes>
      <api>
        <suites>
          <suite name="<suite>">
            <group name="<group>">
              <scheme><scheme_name></scheme>
              ...
            </group>
          </suite>
        </suites>
      </api>
      <var_dictionaries>
        <var_dictionary name="<host_name>" type="host">
          <variables>
            <!-- protected="True" only emitted when the host var is protected;
                 the attribute is absent (not "False") otherwise. -->
            <var name="<std_name_a>" local_name="..." protected="True"/>
            <var name="<std_name_b>" local_name="..."/>
            ...
          </variables>
        </var_dictionary>
        <var_dictionary name="ccpp_api" type="api" parent="<host_name>">
          <variables/>
        </var_dictionary>
        <var_dictionary name="<suite>" type="suite" parent="ccpp_api">
          <variables/>
        </var_dictionary>
        <var_dictionary name="<group>" type="group" parent="<suite>">
          <variables/>
        </var_dictionary>
        <var_dictionary name="<group>_call_list" type="group_call_list"
                        parent="<group>">
          <variables>
            <var name="<std_name>" intent="in" local_name="..."/>
            ...
          </variables>
        </var_dictionary>
        ...
      </var_dictionaries>
      <dependencies/>
    </ccpp_datatable>

Compatibility notes
-------------------
The ``<schemes>`` section uses the same phase element tag names as the new
generator's phase vocabulary (``init``, ``run``, ``timestep_init``,
``timestep_final``, ``final``, ``register``).  ``ccpp_datafile.py`` iterates
scheme children by tag rather than filtering on specific names, so this is
forward-compatible.
"""

import os
import xml.etree.ElementTree as ET
from typing import Dict, List, Optional, Set, Tuple

from generator.suite_resolver import SuiteResolution, iter_phase_calls

_API_DICT_NAME = 'ccpp_api'


def _build_capgen_files(
    root: ET.Element,
    utility_paths: List[str],
    host_file_paths: List[str],
    suite_file_paths: List[str],
) -> None:
    """Append ``<capgen_files>`` to *root*.

    ``<capgen_files>`` lists Fortran sources generated by capgen-ng (utilities,
    the host-facing API, and per-suite caps).  Non-Fortran inspection
    artifacts (e.g. ``.meta`` files, expanded SDFs) live in
    ``<inspection_files>`` and are emitted by :func:`_build_inspection_files`.

    ``host_file_paths`` lists files generated for the host-facing API.  In
    capgen-ng this is the static API (``ccpp_static_api.F90``); the section is
    emitted unconditionally (possibly empty) to keep the schema stable.
    """
    capgen_files = ET.SubElement(root, 'capgen_files')

    utilities = ET.SubElement(capgen_files, 'utilities')
    for path in utility_paths:
        f = ET.SubElement(utilities, 'file')
        f.text = path

    host_files = ET.SubElement(capgen_files, 'host_files')
    for path in host_file_paths:
        f = ET.SubElement(host_files, 'file')
        f.text = path

    suite_files = ET.SubElement(capgen_files, 'suite_files')
    for path in suite_file_paths:
        f = ET.SubElement(suite_files, 'file')
        f.text = path


def _build_inspection_files(
    root: ET.Element,
    suite_meta_paths: Optional[List[str]] = None,
    expanded_sdf_paths: Optional[List[str]] = None,
) -> None:
    """Append ``<inspection_files>`` to *root*.

    Inspection artifacts are non-Fortran outputs that capgen-ng emits for
    debugging and downstream tooling.  They are *not* compiled.  Each kind
    of artifact lives in its own subsection so consumers can pick a specific
    file type or take them all together via ``--inspection-files``.

    Subsections written:

    * ``<suite_meta_files>`` — generated ``ccpp_<suite>.meta`` files (the
      suite-data variable metadata table).
    * ``<expanded_sdf_files>`` — fully expanded suite-definition XML
      (``ccpp_<suite>_expanded.xml``), with any ``<nested_suite>`` references
      resolved.

    The section is always written (possibly with empty subsections) to keep
    the schema stable.
    """
    inspection = ET.SubElement(root, 'inspection_files')

    suite_meta_files = ET.SubElement(inspection, 'suite_meta_files')
    for path in suite_meta_paths or []:
        f = ET.SubElement(suite_meta_files, 'file')
        f.text = path

    expanded_sdf_files = ET.SubElement(inspection, 'expanded_sdf_files')
    for path in expanded_sdf_paths or []:
        f = ET.SubElement(expanded_sdf_files, 'file')
        f.text = path


def _build_schemes(
    root: ET.Element,
    suite_resolutions: List[SuiteResolution],
    scheme_store,
) -> None:
    """Append ``<schemes>`` to *root*.

    Each scheme appears once; its phases are the union of phases seen across
    all suites.  Duplicate scheme names (scheme used in multiple suites) are
    deduplicated — the call_list is the same regardless of which suite uses
    the scheme.
    """
    schemes_elem = ET.SubElement(root, 'schemes')
    seen_scheme_phases: Dict[str, Set[str]] = {}

    for sr in suite_resolutions:
        for rg in sr.groups:
            for phase_name, items in rg.phase_calls.items():
                for rc in iter_phase_calls(items):
                    sname = rc.scheme_name
                    if sname not in seen_scheme_phases:
                        seen_scheme_phases[sname] = set()
                    seen_scheme_phases[sname].add(phase_name)

    for sname in sorted(seen_scheme_phases):
        scheme_elem = ET.SubElement(schemes_elem, 'scheme')
        scheme_elem.set('name', sname)
        for phase in sorted(seen_scheme_phases[sname]):
            phase_elem = ET.SubElement(scheme_elem, phase)
            phase_elem.set('name', sname)
            phase_elem.set('subroutine_name', '{}_{}'.format(sname, phase))
            phase_elem.set('module', sname)
            call_list = ET.SubElement(phase_elem, 'call_list')
            mvars = scheme_store.variables_for(sname, phase)
            if mvars:
                for mv in mvars:
                    var = ET.SubElement(call_list, 'var')
                    var.set('name', mv.standard_name)
                    var.set('intent', mv.intent or '')
                    var.set('local_name', mv.local_name)
                    if mv.diagnostic_name:
                        var.set('diagnostic_name', mv.diagnostic_name)
                    if mv.diagnostic_name_fixed:
                        var.set('diagnostic_name_fixed',
                                mv.diagnostic_name_fixed)


def _build_api(
    root: ET.Element,
    suite_resolutions: List[SuiteResolution],
) -> None:
    """Append ``<api><suites>...</suites></api>`` to *root*."""
    api_elem = ET.SubElement(root, 'api')
    suites_elem = ET.SubElement(api_elem, 'suites')

    for sr in suite_resolutions:
        suite_elem = ET.SubElement(suites_elem, 'suite')
        suite_elem.set('name', sr.suite_name)
        for rg in sr.groups:
            group_elem = ET.SubElement(suite_elem, 'group')
            group_elem.set('name', rg.group_name)
            seen: Set[str] = set()
            for items in rg.phase_calls.values():
                for rc in iter_phase_calls(items):
                    if rc.scheme_name not in seen:
                        seen.add(rc.scheme_name)
                        sch = ET.SubElement(group_elem, 'scheme')
                        sch.text = rc.scheme_name


def _build_var_dictionaries(
    root: ET.Element,
    host_dict,
    host_name: str,
    suite_resolutions: List[SuiteResolution],
) -> None:
    """Append ``<var_dictionaries>`` to *root*.

    Emits one dictionary entry per scope in the lookup chain
    (``host`` → ``api`` → ``suite`` → ``group`` → ``group_call_list``).
    The ``parent`` attribute on each entry preserves the inheritance chain
    that ``ccpp_datafile.py`` walks when resolving ``protected`` and
    ``--exclude-protected``.

    The host dictionary carries one ``<var>`` per entry in *host_dict*
    (host model + control vars).  Each group's call-list dictionary
    carries one ``<var>`` per (standard_name, intent) tuple seen at any
    phase call site in that group.
    """
    if host_dict is None:
        return

    dicts = ET.SubElement(root, 'var_dictionaries')

    host_d = ET.SubElement(dicts, 'var_dictionary')
    host_d.set('name', host_name)
    host_d.set('type', 'host')
    h_vars = ET.SubElement(host_d, 'variables')
    for std_name in sorted(host_dict):
        entry = host_dict[std_name]
        v = ET.SubElement(h_vars, 'var')
        v.set('name', std_name)
        if entry.local_name:
            v.set('local_name', entry.local_name)
        if getattr(entry, 'protected', False):
            v.set('protected', 'True')

    api_d = ET.SubElement(dicts, 'var_dictionary')
    api_d.set('name', _API_DICT_NAME)
    api_d.set('type', 'api')
    api_d.set('parent', host_name)
    ET.SubElement(api_d, 'variables')

    for sr in suite_resolutions:
        suite_d = ET.SubElement(dicts, 'var_dictionary')
        suite_d.set('name', sr.suite_name)
        suite_d.set('type', 'suite')
        suite_d.set('parent', _API_DICT_NAME)
        ET.SubElement(suite_d, 'variables')

        for rg in sr.groups:
            group_d = ET.SubElement(dicts, 'var_dictionary')
            group_d.set('name', rg.group_name)
            group_d.set('type', 'group')
            group_d.set('parent', sr.suite_name)
            ET.SubElement(group_d, 'variables')

            call_d = ET.SubElement(dicts, 'var_dictionary')
            call_d.set('name', '{}_call_list'.format(rg.group_name))
            call_d.set('type', 'group_call_list')
            call_d.set('parent', rg.group_name)
            cl_vars = ET.SubElement(call_d, 'variables')

            seen: Set[Tuple[str, str]] = set()
            for items in rg.phase_calls.values():
                for rc in iter_phase_calls(items):
                    for arg in rc.args:
                        intent = arg.intent or ''
                        key = (arg.standard_name, intent)
                        if key in seen:
                            continue
                        seen.add(key)
                        v = ET.SubElement(cl_vars, 'var')
                        v.set('name', arg.standard_name)
                        if intent:
                            v.set('intent', intent)
                        if arg.scheme_local_name:
                            v.set('local_name', arg.scheme_local_name)


def write_datatable(
    suite_resolutions: List[SuiteResolution],
    scheme_store,
    utility_paths: List[str],
    suite_file_paths: List[str],
    output_root: str,
    host_file_paths: Optional[List[str]] = None,
    dependency_paths: Optional[List[str]] = None,
    suite_meta_paths: Optional[List[str]] = None,
    expanded_sdf_paths: Optional[List[str]] = None,
    host_dict=None,
    host_name: str = 'host',
) -> str:
    """Write ``datatable.xml`` and return its absolute path.

    Parameters
    ----------
    suite_resolutions : list of SuiteResolution
    scheme_store : SchemeStore
    utility_paths : list of str
        Absolute paths to utility Fortran files (e.g. ``ccpp_kinds.F90``).
    suite_file_paths : list of str
        Absolute paths to generated suite cap files.
    output_root : str
        Output directory.
    host_file_paths : list of str, optional
        Absolute paths to host-facing API files (capgen-ng emits
        ``ccpp_static_api.F90`` here).  The ``<host_files>`` section is
        always written (possibly empty).
    dependency_paths : list of str, optional
        Absolute paths of scheme dependency files (collected from
        ``MetadataTable.dependencies``).  Written as ``<dependency>``
        children of the ``<dependencies>`` element.
    suite_meta_paths : list of str, optional
        Absolute paths to generated ``ccpp_<suite>.meta`` files (inspection
        artifacts; written under ``<inspection_files><suite_meta_files>``).
    expanded_sdf_paths : list of str, optional
        Absolute paths to generated ``ccpp_<suite>_expanded.xml`` files
        (inspection artifacts; written under
        ``<inspection_files><expanded_sdf_files>``).

    Returns
    -------
    str
        Absolute path to the written ``datatable.xml``.

    Examples
    --------
    >>> import tempfile, os
    >>> from generator.datatable import write_datatable
    >>> from unittest.mock import MagicMock
    >>> sr = MagicMock()
    >>> sr.suite_name = 'test'
    >>> sr.groups = []
    >>> store = MagicMock()
    >>> with tempfile.TemporaryDirectory() as d:
    ...     path = write_datatable([sr], store, [], [], d)
    ...     os.path.basename(path)
    'datatable.xml'
    """
    os.makedirs(output_root, exist_ok=True)

    root = ET.Element('ccpp_datatable')
    root.set('version', '1.0')

    _build_capgen_files(
        root, utility_paths, host_file_paths or [],
        suite_file_paths,
    )
    _build_inspection_files(
        root,
        suite_meta_paths=suite_meta_paths,
        expanded_sdf_paths=expanded_sdf_paths,
    )
    _build_schemes(root, suite_resolutions, scheme_store)
    _build_api(root, suite_resolutions)
    _build_var_dictionaries(root, host_dict, host_name, suite_resolutions)

    deps_elem = ET.SubElement(root, 'dependencies')
    for dep in sorted(set(dependency_paths or [])):
        d = ET.SubElement(deps_elem, 'dependency')
        d.text = dep

    tree = ET.ElementTree(root)
    ET.indent(tree, space='  ')
    out_path = os.path.join(os.path.abspath(output_root), 'datatable.xml')
    tree.write(out_path, encoding='unicode', xml_declaration=True)

    # Ensure file ends with a newline.
    with open(out_path, 'a') as fh:
        fh.write('\n')

    return out_path
